addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: c519da2b-0cd6-449a-9efc-55b43b1ca2b3
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-prod.public-swarm.devfactory.com/travisWebHookListener?build_id=c519da2b-0cd6-449a-9efc-55b43b1ca2b3
script: mvn test-compile -Dgpg.skip=true
sudo: 'false'
# Modified by Insights Service at 2016-09-21 00:35:44.837095
