addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    target_paths: 75cdab2e-d585-4ae6-ac02-d2c5b7a6cb87
after_success:
- ./df-build.sh
before_install:
- sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g'
  $HOME/.m2/settings.xml
branches: ''
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-prod1.public-swarm.devfactory.com/travisWebHookListener?build_id=75cdab2e-d585-4ae6-ac02-d2c5b7a6cb87
script: mvn test-compile -Dgpg.skip=true
sudo: 'false'
# Modified by Insights Service at 2016-09-26 10:24:16.884557
